<?php


function page_alter_page_alter(&$page){
/**
 *
 * ADD META TAGS FOR SPECIFIC CODES
 *
 * name = "Page Alter"
 * description = "hook_page_alter()."
 * core = 7.x
 * package = SN Custom
 *                    
 */

/*
  dpm('arg0: ' . arg(0));
  dpm('arg1: ' . arg(1));
  dpm('arg2: ' . arg(2));
  dpm('arg3: ' . arg(3));
*/


$node = node_load(arg(1));

$front_url = variable_get('site_frontpage', 'node');
$front_url = trim($front_url, '/');
$front = explode('/', $front_url);
if( $front[0]=='node' && ctype_digit($front[1]) ) {
  $front_nid = $front[1];
}
echo $front_nid;

if ( $node->nid == $front_nid ) {

   $content = $node->metatags['und']['description']['value'];



   $meta_description = array(
            '#type' => 'html_tag',
            '#tag' => 'meta',
            '#attributes' => array(
                'name' => 'description',
                'content' =>  $content
            )
     );
      drupal_add_html_head( $meta_description, 'meta_description' );

  }

}
